#print("Hello world\nHello world")
#print("Day 1 - Python print function")
#print("The function is declared like this:")
#print("print('what to print')")
#print("Hello " + "minister")
#print("Day 1 - striung Manipulation")
#print('String concatenation is done with the "+ " sign.')
#print('e.g print("Hello" + " world")')
#print("New lines can be creagted with a backlash and n.")
#input function is used to make prompt i.e request#
#print("Hello " + input("What is your name? "))
#print ( len( input("what is your name? ") ))
#name = input("what is your name? ")
#length = len(name)
#print (length)
#a = input("a:")
#b = input("b:")
#a = b 
#b = c
#print(a)
#print(b)
#lst = [["ade", "ayo", "omo", "idowu"] ["akin", "umar", "alaba", "igan", "iyo"] ["ede", "edo", "imo"]]
#print(lst[0][1])

